### ISSUE TITLE
cancelEvent not working

### ISSUE THREAD

**Issue by LenaDooms** [novuhq/novu-php#16]
the `cancelEvent` function in `ManagesTriggers` results in an error. In its body, `delete` returns a boolean, as the response body of the delete request is empty. When this boolean value `$response` is used to create a `Trigger object`, an error is thrown, since `Trigger` expects an array, not a boolean.

**Comment by unicodeveloper** [comment]
Thanks for mentioning this. Taking a look at it right away @LenaDooms

**Comment by LenaDooms** [comment]
thanks for the quick follow up!

**Comment by unicodeveloper** [comment]
This has been fixed in the latest release @LenaDooms

**Comment by LenaDooms** [comment]
Amazing, thank you @unicodeveloper !!
