### ISSUE TITLE
[NV-PHP-3] API 🚀: Manage Layouts 

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-php#31]
There is no section to manage layouts from this SDK. Add the necessary action and methods to make it possible.

API references and methods/features required.

- Create Layouts - https://docs.novu.co/api-reference/layouts/layout-creation
- Get Layout - https://docs.novu.co/api-reference/layouts/get-layout
- Delete Layout - https://docs.novu.co/api-reference/layouts/delete-layout
- Update Layout - https://docs.novu.co/api-reference/layouts/update-a-layout
- Set default Layout - https://docs.novu.co/api-reference/layouts/set-default-layout
- Filter Layouts - https://docs.novu.co/api-reference/layouts/filter-layouts

**Comment by Eazybright** [comment]
@unicodeveloper  i would love to work on this.

**Comment by unicodeveloper** [comment]
@Eazybright I just assigned you to this.

**Comment by Eazybright** [comment]
> @Eazybright I just assigned you to this and updated the docs link to point to the correct docs.

Noted. Thanks

**Comment by Eazybright** [comment]
@unicodeveloper PR raised: https://github.com/novuhq/novu-php/pull/55
