### ISSUE TITLE
[NV-PHP-5] API 🚀: Add Tenants Feature - New Tenants API

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-php#33]
The tenants feature just became available this week in v0.19 on the UI and API.

This SDK needs to be updated to have this feature.

API reference: https://docs.novu.co/api-reference/tenants/

**Comment by Eazybright** [comment]
@unicodeveloper i would love to work on this.

**Comment by kraynel** [comment]
@Eazybright oh I started working on that before your comment, sorry!

**Comment by Eazybright** [comment]
noted
