### ISSUE TITLE
NV-PHP-7] API 🚀: Add Messages Feature 

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-php#50]
The messages endpoints can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Messages Feature

Get Messages - https://docs.novu.co/api-reference/messages/get-messages
Delete Message - https://docs.novu.co/api-reference/messages/delete-message

**Comment by Eazybright** [comment]
@Cliftonz i would love to work on this

**Comment by codelikesuraj** [comment]
@Eazybright are you actively on this?

**Comment by Eazybright** [comment]
Yes I am

**Comment by Eazybright** [comment]
@Cliftonz The message feature already exist. This is an addition to what was already implemented - https://github.com/novuhq/novu-php/pull/56
