### ISSUE TITLE
NV-PHP-6] API 🚀: Add Blueprints Feature 

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-php#51]
This feature needs to be added to the SDK.

The methods and API reference below:

- Get blueprints - https://docs.novu.co/api-reference/get-v1blueprints
- Get blueprints group by category - https://docs.novu.co/api-reference/get-v1blueprints

**Comment by unicodeveloper** [comment]
Assigning this to you now @TheAbhishekIN

**Comment by unicodeveloper** [comment]
Assigned 🎊

**Comment by TheAbhishekIN** [comment]
Hey @unicodeveloper , I have submitted the PR https://github.com/novuhq/novu-php/pull/53
